require 'open-uri'
require 'rexml/document'
require 'delegate'
require 'json'
require 'rss'

require_relative 'syobocal/util.rb'
require_relative 'syobocal/calchk.rb'
require_relative 'syobocal/db.rb'
require_relative 'syobocal/json.rb'
require_relative 'syobocal/rss.rb'
require_relative 'syobocal/rss2.rb'
